### ISSUE TITLE
Question / Remark : Refit <> RestEase

### ISSUE THREAD

**Issue by StefH** [davidfowl/RestSample#2]
Just a remark, you could also have used https://github.com/canton7/RestEase which has the same (+more) functionality.

**Comment by clairernovotny** [comment]
RestEase uses runtime code-gen, which means it does not work on AOT platforms (like iOS). Refit does compile-time code-gen, so it works everywhere and has no startup penalty. 

If there's additional functionality that you'd like to see in Refit, please file an issue (or submit a PR). Contributions welcome!

**Comment by StefH** [comment]
Keep up the good work. Closing issue.
